services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
        interval: 3s
        retries: 10

  app:
    build:
      context: .
      args:
        HTTP_PORT: ${HTTP_PORT}
    depends_on:
      db:
        condition: 'service_healthy'
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"

volumes:
  db-data: