basePath: /
definitions:
  dto.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  dto.SubscriptionPayload:
    properties:
      end_date:
        example: 12-2025
        type: string
      price:
        example: 400
        minimum: 0
        type: integer
      service_name:
        example: Yandex Plus
        type: string
      start_date:
        example: 07-2025
        type: string
      user_id:
        example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
        type: string
    required:
    - price
    - service_name
    - start_date
    - user_id
    type: object
  dto.SubscriptionResponse:
    properties:
      end_date:
        example: 12-2025
        type: string
      price:
        example: 400
        type: integer
      service_name:
        example: Yandex Plus
        type: string
      start_date:
        example: 07-2025
        type: string
      user_id:
        example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
        type: string
    type: object
  dto.SubscriptionUpdatePayload:
    properties:
      end_date:
        example: 12-2025
        type: string
      price:
        example: 400
        minimum: 0
        type: integer
      start_date:
        example: 07-2025
        type: string
    required:
    - price
    - start_date
    type: object
  dto.TotalResponse:
    properties:
      total:
        type: integer
    type: object
info:
  contact: {}
  description: REST‑сервис для учёта онлайн‑подписок пользователей.
  title: Subscriptions Service API
  version: "1.0"
paths:
  /subscriptions:
    get:
      parameters:
      - description: ID пользователя
        in: query
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.SubscriptionResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Список подписок пользователя
    post:
      consumes:
      - application/json
      description: Добавляет новую запись о подписке
      parameters:
      - description: data
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/dto.SubscriptionPayload'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Создать подписку
  /subscriptions/{user_id}/{service_name}:
    delete:
      parameters:
      - description: ID пользователя
        in: path
        name: user_id
        required: true
        type: string
      - description: Название сервиса
        in: path
        name: service_name
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Удалить подписку
    get:
      parameters:
      - description: ID пользователя
        in: path
        name: user_id
        required: true
        type: string
      - description: Название сервиса
        in: path
        name: service_name
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SubscriptionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Получить подписку
    put:
      parameters:
      - description: ID пользователя
        in: path
        name: user_id
        required: true
        type: string
      - description: Название сервиса
        in: path
        name: service_name
        required: true
        type: string
      - description: Обновлённая подписка
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/dto.SubscriptionUpdatePayload'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SubscriptionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Обновить подписку
  /subscriptions/summary:
    get:
      description: Считает суммарную стоимость подписок за период
      parameters:
      - description: ID пользователя
        in: query
        name: user_id
        required: true
        type: string
      - description: Начало периода MM-YYYY
        in: query
        name: from
        required: true
        type: string
      - description: Конец периода MM-YYYY
        in: query
        name: to
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TotalResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Сумма подписок
swagger: "2.0"
